name: Create release

on:
  push:
    tags:
      - v* # 当有以 "v" 开头的 tag push 时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
